#!/bin/bash

usersickrage="contyteam"


TORRENT_PATH=$1
TORRENT_NAME=$2
TORRENT_LABEL=$3

sh /home/"$usersickrage"/.filebot/filebot.sh --lang fr -script fn:amc --output "/home/"$usersickrage"/Media" --log-file "/home/"$usersickrage"/.session/amc.log" --action symlink --conflict override -non-strict --def music=y artwork=y "ut_dir=$TORRENT_PATH" "ut_kind=multi" "ut_title=$TORRENT_NAME" "ut_label=$TORRENT_LABEL" &
